spring.application.name=backend

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=quickbite

#By default ,spring boot does not do indexing by this command spring boot will make automatic index
spring.data.mongodb.auto-index-creation = true